// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofbqxdktyzawqqnxmocn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mYnF4ZGt0eXphd3Fxbnhtb2NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjUyNDksImV4cCI6MjA2NzA0MTI0OX0.Q324cm4nSgV7up3LW91RBqV2SQ2ihHQ-1LW50h3JE9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});